//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class colaDistribucionLog
    {
        public int id { get; set; }
        public Nullable<int> idColaDistribucion { get; set; }
        public Nullable<int> idJuicio { get; set; }
        public Nullable<decimal> montoJuicio { get; set; }
        public Nullable<decimal> montoPromedio { get; set; }
        public Nullable<int> puntajeRestante { get; set; }
        public Nullable<int> puntajeRestado { get; set; }
        public Nullable<int> puntajeRestanteActualizado { get; set; }
        public Nullable<bool> habilitado { get; set; }
        public Nullable<int> pasada { get; set; }
        public Nullable<int> posicionActual { get; set; }
        public Nullable<int> puntajeApoderado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string numeroTitulo { get; set; }
        public Nullable<int> idTipoEvento { get; set; }
    
        public virtual colaDistribucion colaDistribucion { get; set; }
    }
}
