//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class fiscaliaEntities : DbContext
    {
        public fiscaliaEntities()
            : base("name=fiscaliaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<colaDistribucion> colaDistribucions { get; set; }
        public virtual DbSet<colaDistribucionLog> colaDistribucionLogs { get; set; }
        public virtual DbSet<tiposDistribucione> tiposDistribuciones { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<Juicios_Registro> Juicios_Registro { get; set; }
        public virtual DbSet<persona> personas { get; set; }
    
        public virtual ObjectResult<GetJuiciosByUsuario_Result> GetJuiciosByUsuario(Nullable<int> idUsuario)
        {
            var idUsuarioParameter = idUsuario.HasValue ?
                new ObjectParameter("idUsuario", idUsuario) :
                new ObjectParameter("idUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetJuiciosByUsuario_Result>("GetJuiciosByUsuario", idUsuarioParameter);
        }
    }
}
