//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tiposDistribucione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tiposDistribucione()
        {
            this.colaDistribucions = new HashSet<colaDistribucion>();
        }
    
        public int id { get; set; }
        public string tipoDistribucion { get; set; }
        public Nullable<decimal> montoPromedio { get; set; }
        public Nullable<bool> distribucionPorCola { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<colaDistribucion> colaDistribucions { get; set; }
    }
}
