//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public usuario()
        {
            this.colaDistribucions = new HashSet<colaDistribucion>();
        }
    
        public int id { get; set; }
        public byte[] sid { get; set; }
        public string apellido { get; set; }
        public string nombres { get; set; }
        public Nullable<int> idTipoUsuario { get; set; }
        public Nullable<int> idSubsecretaria { get; set; }
        public Nullable<bool> activo { get; set; }
        public string motivoBaja { get; set; }
        public bool crearADUser { get; set; }
        public Nullable<System.DateTime> ultimoLogin { get; set; }
        public Nullable<System.DateTime> ultimoLogout { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public string userName { get; set; }
        public Nullable<int> idUsuarioBaja { get; set; }
        public string codigoSeguridad { get; set; }
        public string tratamiento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<colaDistribucion> colaDistribucions { get; set; }
    }
}
